[project]
name = "bookstores-inventory-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "DanielRamirez404", email = "danielramirezabou404@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.142.2",
]

[project.scripts]
bookstores-inventory-api = "bookstores_inventory_api:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
